# Scikit-Learn (sklearn)

* is a python machin elearning library
* helps us to build machine learning models to make predictions or learn patterns within that data and then make predictions
* it also implements tools to help us evaluate those predictions

## why?
* build on numpy and matplotlib (and python)
* has many in-built machine learning models
* methods to evaluate your machine learning models
* very well-designed API

# scikit-learn workflow
* get data ready
* pick a model (to suit your problem)
* fit the model to the data and make a prediction
  * find patterns
* evaluate the model
* improve through experimentation
* save and reload your trained model

# Agenda

0. an end-tyot end scikit-learn workflow
1. geeting the data ready
2. choose the right estimator/algorithm for our problems
3. fit the model/ algorithm and use it to make predictions on our data
4. evaluating a model
5. improve a model
6. save and load a trained model
7. putting it all togeather

# 0. an end-to-end scikit-learn workflow

### 1. get the data ready

In [1]:
# stardard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
heart_disease = pd.read_csv("./data/heart-disease.csv")
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [2]:
# create X (feature matrix)
x = heart_disease.drop ("target", axis = 1)

# create Y (labels)
y = heart_disease["target"]

### 2. choosing the right model and hyoerparameters

In [3]:
# classification machine learning model
# capable of learning patterns and data and then classifying whenther a sample is one (a row) or another 
#(i.e., this or that)
from sklearn.ensemble import RandomForestClassifier 
# clf - classifier in scikit learn (ALT: model) 
# instantiate the classifier class in clf
clf = RandomForestClassifier()
# keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

### 3. fit the model to data

In [4]:
from sklearn.model_selection import train_test_split

# split out data from x and y into x_train (training data), y_train, x_test (testing data), y_test
# test_size 0.2 => 20% ; that means 80% of data for training
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [5]:
# ask classification model (randomForest) to find patterns in the training set of data
clf.fit(x_train, y_train)

RandomForestClassifier()

In [6]:
# 80% data which was set as training data and patterns were asked to be found in input data
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
110,64,0,0,180,325,0,1,154,1,0.0,2,0,2
284,61,1,0,140,207,0,0,138,1,1.9,2,1,3
13,64,1,3,110,211,0,0,144,1,1.8,1,0,2
286,59,1,3,134,204,0,1,162,0,0.8,2,2,2
62,52,1,3,118,186,0,0,190,0,0.0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,60,0,2,102,318,0,1,160,0,0.0,2,1,2
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2
278,58,0,1,136,319,1,0,152,0,0.0,2,2,2
37,54,1,2,150,232,0,0,165,0,1.6,2,0,3
124,39,0,2,94,199,0,1,179,0,0.0,2,0,2

In [7]:
# 20% data which was set as testing data
x_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2
64,58,1,2,140,211,1,0,165,0,0.0,2,0,2
292,58,0,0,170,225,1,0,146,1,2.8,1,2,1
101,59,1,3,178,270,0,0,145,0,4.2,0,0,3
133,41,1,1,110,235,0,1,153,0,0.0,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,34,1,3,118,182,0,0,174,0,0.0,2,0,2
79,58,1,2,105,240,0,0,154,1,0.6,1,0,3
146,44,0,2,118,242,0,1,149,0,0.3,1,1,2
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3
52,62,1,2,130,231,0,1,146,0,1.8,1,3,3

In [8]:
# make a prediction
import numpy as np
# y_label = clf.predict(np.array([0, 2, 3, 4]))

In [9]:
# now that the patterns have been recognised in x_train ,
# using those patterns we are asking it to predict using the x_test data and save it as y predictions
y_preds = clf.predict(x_test)
y_preds

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0], dtype=int64)

In [10]:
# the y prediction (y_predict) seem to be simmilarto y_test with 0s and 1s
y_test

6      1
64     1
292    0
101    1
133    1
      ..
58     1
79     1
146    1
176    0
52     1
Name: target, Length: 61, dtype: int64

##### note: we can see that the predictions of y (y_preds) made by predicting the x_test data (similar to x_train) is similar to the expecrted y data (y_test)

### 4. evaluate the model

In [11]:
# return mean accuracy of the given test data and labels
# shape of data must match
clf.score(x_train, y_train)

1.0

In [12]:
clf.score(x_test, y_test)

0.7868852459016393

In [13]:
# functions for evaluating the performance of classification models.
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_preds)) # true labels vs predictions

              precision    recall  f1-score   support

           0       0.77      0.74      0.75        27
           1       0.80      0.82      0.81        34

    accuracy                           0.79        61
   macro avg       0.78      0.78      0.78        61
weighted avg       0.79      0.79      0.79        61

In [14]:
confusion_matrix(y_test, y_preds)

array([[20,  7],
       [ 6, 28]], dtype=int64)

In [15]:
accuracy_score(y_test, y_preds)

0.7868852459016393

### 5. improve a medel

In [16]:
# try different amount of n estimators (one of the parameters to try and immprove)
# eg:
np.random.seed(42)
for i in range (10, 100, 10):
    print(f"Trying model with {i} estimators") # f denotes f-string: formatted string literal
    clf = RandomForestClassifier(n_estimators = i).fit(x_train, y_train) # adjusting parameters
    print(f"Model accurecy on test set: {clf.score(x_test, y_test) * 100:.2f}%") # shrtcut in py using f-string syntax: similar to round(num, 2)
    print(" ")

Trying model with 10 estimators
Model accurecy on test set: 77.05%

Trying model with 20 estimators
Model accurecy on test set: 81.97%

Trying model with 30 estimators
Model accurecy on test set: 81.97%

Trying model with 40 estimators
Model accurecy on test set: 80.33%

Trying model with 50 estimators
Model accurecy on test set: 83.61%

Trying model with 60 estimators
Model accurecy on test set: 83.61%

Trying model with 70 estimators
Model accurecy on test set: 83.61%

Trying model with 80 estimators
Model accurecy on test set: 80.33%

Trying model with 90 estimators
Model accurecy on test set: 83.61%

##### we can see that by adjusting the hyper parameters of our model from 10 (default) to 20, we are able to ncrese score from the actual accuracy to teh l;ast iterated accuracy

### 6. save the model and load it

In [17]:
# save model with py's pickle library
import pickle

pickle.dump(clf, open("./exported/random_forest_model_1.pkl", "wb")) # write in binary

In [18]:
# load the saved model
loaded_model = pickle.load(open("./exported/random_forest_model_1.pkl", "rb")) # read binary
loaded_model.score(x_test, y_test)

0.8360655737704918

##### note: the loaded model is observed to have improved upto the last iterated estimator... the actual accuracy to teh l;ast iterated accuracy